//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.15 at 04:49:13 PM BST 
//


package com.thecrunchycorner.peacockint.updatecustwsmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CustomerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CustomerId" type="{http://www.thecrunchycorner.com/peacockInt/schemas}CustomerIdType"/>
 *         &lt;element name="CustomerOrg" type="{http://www.thecrunchycorner.com/peacockInt/schemas}CustomerOrgType"/>
 *         &lt;element name="CustomerStatus" type="{http://www.thecrunchycorner.com/peacockInt/schemas}CustomerStatusType"/>
 *         &lt;element name="CustomerFname" type="{http://www.thecrunchycorner.com/peacockInt/schemas}CustomerFnameType"/>
 *         &lt;element name="CustomerSname" type="{http://www.thecrunchycorner.com/peacockInt/schemas}CustomerSnameType"/>
 *         &lt;element name="CustomerDOB" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="CustomerStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="CustomerEndDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomerType", namespace = "http://www.thecrunchycorner.com/peacockInt/schemas", propOrder = {
    "customerId",
    "customerOrg",
    "customerStatus",
    "customerFname",
    "customerSname",
    "customerDOB",
    "customerStartDate",
    "customerEndDate"
})
public class CustomerType {

    @XmlElement(name = "CustomerId", namespace = "http://www.thecrunchycorner.com/peacockInt/schemas", required = true)
    protected String customerId;
    @XmlElement(name = "CustomerOrg", namespace = "http://www.thecrunchycorner.com/peacockInt/schemas", required = true)
    protected String customerOrg;
    @XmlElement(name = "CustomerStatus", namespace = "http://www.thecrunchycorner.com/peacockInt/schemas", required = true)
    protected CustomerStatusType customerStatus;
    @XmlElement(name = "CustomerFname", namespace = "http://www.thecrunchycorner.com/peacockInt/schemas", required = true)
    protected String customerFname;
    @XmlElement(name = "CustomerSname", namespace = "http://www.thecrunchycorner.com/peacockInt/schemas", required = true)
    protected String customerSname;
    @XmlElement(name = "CustomerDOB", namespace = "http://www.thecrunchycorner.com/peacockInt/schemas", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar customerDOB;
    @XmlElement(name = "CustomerStartDate", namespace = "http://www.thecrunchycorner.com/peacockInt/schemas", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar customerStartDate;
    @XmlElement(name = "CustomerEndDate", namespace = "http://www.thecrunchycorner.com/peacockInt/schemas", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar customerEndDate;

    /**
     * Gets the value of the customerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerId(String value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the customerOrg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerOrg() {
        return customerOrg;
    }

    /**
     * Sets the value of the customerOrg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerOrg(String value) {
        this.customerOrg = value;
    }

    /**
     * Gets the value of the customerStatus property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerStatusType }
     *     
     */
    public CustomerStatusType getCustomerStatus() {
        return customerStatus;
    }

    /**
     * Sets the value of the customerStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerStatusType }
     *     
     */
    public void setCustomerStatus(CustomerStatusType value) {
        this.customerStatus = value;
    }

    /**
     * Gets the value of the customerFname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerFname() {
        return customerFname;
    }

    /**
     * Sets the value of the customerFname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerFname(String value) {
        this.customerFname = value;
    }

    /**
     * Gets the value of the customerSname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerSname() {
        return customerSname;
    }

    /**
     * Sets the value of the customerSname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerSname(String value) {
        this.customerSname = value;
    }

    /**
     * Gets the value of the customerDOB property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCustomerDOB() {
        return customerDOB;
    }

    /**
     * Sets the value of the customerDOB property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCustomerDOB(XMLGregorianCalendar value) {
        this.customerDOB = value;
    }

    /**
     * Gets the value of the customerStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCustomerStartDate() {
        return customerStartDate;
    }

    /**
     * Sets the value of the customerStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCustomerStartDate(XMLGregorianCalendar value) {
        this.customerStartDate = value;
    }

    /**
     * Gets the value of the customerEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCustomerEndDate() {
        return customerEndDate;
    }

    /**
     * Sets the value of the customerEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCustomerEndDate(XMLGregorianCalendar value) {
        this.customerEndDate = value;
    }

}
