//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.26 at 05:20:06 PM BST 
//


package com.thecrunchycorner.peacockmybank.regvalwsmodel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.thecrunchycorner.peacockint.regvalwsmodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.thecrunchycorner.peacockint.regvalwsmodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CustRegValidationResponse }
     * 
     */
    public CustRegValidationResponse createCustRegValidationResponse() {
        return new CustRegValidationResponse();
    }

    /**
     * Create an instance of {@link CustRegValidationRequest }
     * 
     */
    public CustRegValidationRequest createCustRegValidationRequest() {
        return new CustRegValidationRequest();
    }

    /**
     * Create an instance of {@link CustomerType }
     * 
     */
    public CustomerType createCustomerType() {
        return new CustomerType();
    }

}
