//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.06 at 01:12:12 PM BST 
//
// make sure xjc doesn't overwrite package-info.java: use -npa option

@javax.xml.bind.annotation.XmlSchema(
  namespace = "http://www.thecrunchycorner.com/peacockInt/schemas",
  xmlns = {
    @javax.xml.bind.annotation.XmlNs(namespaceURI= "http://www.thecrunchycorner.com/peacockInt/schemas", prefix = "bnk") ,
    @javax.xml.bind.annotation.XmlNs(namespaceURI= "http://www.w3.org/2001/XMLSchema-instance", prefix = "xsi") 
  }, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED
)
package com.thecrunchycorner.peacockmybank.regvalwsmodel;
